# -*- coding: utf-8 -*-
"""Prompts_ui.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1up9CqxzNmRgS7WYs_mf19Vj3UFyTaMzR
"""

# 1. Install required packages
!pip install streamlit pyngrok --quiet

!pip install -qU langchain-huggingface

# 2. Import required libraries
from pyngrok import ngrok , conf
import threading, time, os

import secret

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile secret.py

# 4. Function to run Streamlit
def run_streamlit():
    os.system("streamlit run app.py --server.port 8501 --server.headless true")

# 5. Start Streamlit in a background thread
threading.Thread(target=run_streamlit).start()

# 6. Give it time to start
time.sleep(3)

conf.get_default().auth_token = secret.NGROK_AUTH_TOKEN

ngrok.kill()

# 7. Create a public URL
public_url = ngrok.connect(8501)
print(f"Your Streamlit app is live at: {public_url}")